### ISSUE TITLE
Long types, table readability

### ISSUE THREAD

**Issue by petermikitsh** [hipstersmoothie/storybook-addon-react-docgen#100]
I have some components who's prop types are a lot of text. For example, my Icon component is one of roughly 1,000 strings (enum). So it's a lot of scrolling to get to the next prop, when the propTypes data is 16,000px tall:

<img width="1057" alt="Screen Shot 2020-06-04 at 5 02 40 PM" src="https://user-images.githubusercontent.com/1571918/83822200-39466f80-a685-11ea-9268-9527c4371964.png">

Thoughts on having a max-height for types, with overflow scroll?

**Comment by hipstersmoothie** [comment]
Yeah this could probably be improved. I factored out all the renders but haven't integrated them

repo: https://github.com/hipstersmoothie/storybook-pretty-props

[That one in particular](https://hipstersmoothie.github.io/storybook-pretty-props/?path=/story/prettyproptype--enum)

We could probably make it look like the [shape renderer](https://hipstersmoothie.github.io/storybook-pretty-props/?path=/story/prettyproptype--shape) and have it expand.

It would look nice if it was formatted like a long type with prettier:

```
oneOf 
  | 'one'
  | 'two'
  | 'three'
```

Then the collapsed state (show like 23-36 characters)

```
oneOf = 'one' | 'two' | ...
```

If you make a PR to storybook-pretty-props i'll integrate it here 🚀

**Comment by petermikitsh** [comment]
Fixed in: 

- https://github.com/hipstersmoothie/storybook-pretty-props/pull/1
- https://github.com/hipstersmoothie/storybook-addon-react-docgen/pull/102

**Comment by gsccheng** [comment]
@hipstersmoothie How can the lines be maximized programmatically? Looks like clicking the ellipsis button is the only way to toggle this and it is always set to minimized by default (e.g. for the `oneOf` type)?
