### ISSUE TITLE
GitHub node-fetch security alert; remove dependency on react-addons-create-fragment

### ISSUE THREAD

**Issue by kevinzang** [hipstersmoothie/storybook-addon-react-docgen#117]
<details><summary>node-fetch security alert</summary>

### Remediation
Upgrade **node-fetch** to version **2.6.1** or later. For example:

```
node-fetch@^2.6.1:
  version "2.6.1"
```

*Always verify the validity and compatibility of suggestions with your codebase.*

### Details
**GHSA-w7rc-rwvf-8q5r**
low severity
**Vulnerable versions:** < 2.6.1
**Patched version:** 2.6.1

### Impact
Node Fetch did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure.

For most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example: If you don't double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.

### Patches
We released patched versions for both stable and beta channels:

For `v2`: 2.6.1
For `v3`: 3.0.0-beta.9

### Workarounds
None, it is strongly recommended to update as soon as possible.

### For more information
If you have any questions or comments about this advisory:

- Open an issue in [node-fetch](https://github.com/node-fetch/node-fetch/issues/new?assignees=&labels=question&template=support-or-usage.md&title=Question%3A+)
- Contact one of the core maintainers.
</details>

The dependency is `storybook-addon-react-docgen` uses `react-addons-create-fragment@^15.6.2`, which uses [`fbjs@^0.8.4`](https://github.com/facebook/fbjs/blob/v0.8.17/package.json), which uses [`isomorphic-fetch@^2.1.1`](https://github.com/matthew-andrews/isomorphic-fetch/blob/v2.2.1/package.json), which uses `node-fetch@^1.0.1`.

[`react-addons-create-fragment` is no longer maintained](https://www.npmjs.com/package/react-addons-create-fragment), so it is unlikely that there will be a v15.X.X that resolves the issue. I'm therefore creating this issue in hopes that `storybook-addon-react-docgen` can resolve the issue by removing its dependency on `react-addons-create-fragment`.

**Comment by hipstersmoothie** [comment]
PRs welcome!

**Comment by kevinzang** [comment]
@hipstersmoothie what version of Yarn does this project use?

I think `react-addons-create-fragment` can simply be uninstalled. It's no longer used as of the TypeScript rewrite in https://github.com/hipstersmoothie/storybook-addon-react-docgen/pull/110.

But when I ran `yarn remove react-addons-create-fragment`, all of the `integrity` lines were removed from the yarn.lock, so I guess I'm not using the expected version of yarn.

Is there anything else I need to know in order to contribute to this project?

**Comment by hipstersmoothie** [comment]
Still on yarn v1. I'd assume that either some does need updating or the lock file needs part of it regenerated

**Comment by kevinzang** [comment]
OK I had v1.9.4. I upgraded to v1.10.0 (per https://github.com/yarnpkg/yarn/issues/6440).

PR to remove `react-addons-create-fragment`: https://github.com/hipstersmoothie/storybook-addon-react-docgen/pull/118.

**Comment by kevinzang** [comment]
I'm closing this issue I created as I was able to work around the security alert by upgrading to Storybook v6 and using the default react-docgen.
