### ISSUE TITLE
[Question] alternatives for `react-docgen-typescript-loader`

### ISSUE THREAD

**Issue by francoismassart** [hipstersmoothie/storybook-addon-react-docgen#137]
Hi 👋 
I read in the docs that typescript projects should use [react-docgen-typescript-loader](https://github.com/strothj/react-docgen-typescript-loader), unfortunately this loader's repo is archived and was last updated in late 2020.

Do you know any alternative loader that could work with your addon + typescript ?

Thank you 🙏

**Comment by hipstersmoothie** [comment]
You should use https://www.npmjs.com/package/react-docgen-typescript-plugin
