### ISSUE TITLE
error: Check the top-level render call using <Styled(div)>

### ISSUE THREAD

**Issue by duckscofield** [hipstersmoothie/storybook-addon-react-docgen#18]
When I installed it on storybook v5, i got this error message

**Comment by e2o** [comment]
Same here, stacktrace:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Styled(div)>. See https://fb.me/react-warning-keys for more information.
    in PropsTable
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```

**Comment by Mindaugas-Jacionis** [comment]
For me it worked briefly and then I got the same error, from stacktrace it is hard to identify what's happening. Anyone has any ideas for some quick-patch? 🙂

**Comment by hipstersmoothie** [comment]
If you can find a fix I'll merge it 🚀

**Comment by Mindaugas-Jacionis** [comment]
Not promising anything. If I find an hour or two of time I will definitely try to mingle with it, but if someone wants to jump in - do it 😉 The more the merrier. 

I tried to open my localhost storybooks on:
Chrome, Opera, Firefox, Brave, and MS Edge Canary for OSx(the new one with v8). 
All have the error in the console, but props are still displayed in prop table. Except for Chrome, this one was failing even to show, so I got curious and tried in incognito. And of course, it worked(error in the console, but props table displayed). Something is just not right with the latest chrome. Even if I turn off all of my extensions, clear the cookies and cache of the browser on the regular mode it just crashes.

If someone stumbles upon the issue and gets his/her/they hands on the issue resolution first - hope this info is helpful.

**Comment by Mindaugas-Jacionis** [comment]
Also, I've check prod build and issue is not there. No console errors and props table shows up on all browsers mentioned in my comment above, including latest Chrome.

**Comment by sheldonj** [comment]
You wouldn't see this error in a production build because it's the standard react key error which wont' show using production react.

**Comment by jnthnwn** [comment]
found a similar issue with a fix on another addon: https://github.com/truffls/storybook-addon-intl/issues/32#issuecomment-477820601

**Comment by hipstersmoothie** [comment]
close via #22
