### ISSUE TITLE
New Project with Storybook 5.2 + preset-typescript isn't showing prop tables

### ISSUE THREAD

**Issue by mattfelten** [hipstersmoothie/storybook-addon-react-docgen#75]
I was having trouble upgrading to newer versions of Storybook with Typescript so I made a new test project to get the config fully working. The last step is that the Props tab is having trouble with prop types.

With functional components, prop types don't show up at all.
![](https://p195.p4.n0.cdn.getcloudapp.com/items/geuY79qw/Screen+Shot+2019-11-11+at+3.07.05+PM.png?v=b00cabd535829b2a88738a7e014a214d)

With class components, prop types only show up for props that have default values, and even can't display the type, just the default value.
![](https://p195.p4.n0.cdn.getcloudapp.com/items/qGuzbevv/Screen+Shot+2019-11-11+at+3.07.08+PM.png?v=f6929a982bc01ffacba20384ebf54f4a)

Any ideas for what I'm missing here?

---

Test repo: https://github.com/mattfelten/storybook-preset-typescript-test

**Comment by mattfelten** [comment]
For some crazy reason I got it to work by changing how I'm declaring the components.
```
const MyComponent: React.FC<Props> = ...
// should be
const MyComponent: FC<Props> = ...

class MyComponent extends React.Component<Props> { ...
// should be
class MyComponent extends Component<Props> { ...
```

See commit here: https://github.com/mattfelten/storybook-preset-typescript-test/commit/1132426e7f7e1a8d356f8da2b981fd612a79d056

This should probably be documented way better than it is.

**Comment by hipstersmoothie** [comment]
I'll take a look but here is a quick tip: don't use FC.

explanation:

I’ve found that in general you don’t want to use React.FC. Once you use that you lose the defaultProps experience.

Using React.FC:

```tsx
interface CardProps {
  size?: 'small' | 'large';
}

// The type of size will be "string | undefined"
// You will either have to repeat your default value
// Or write a helper type the figures out what is defaulted
const Card: React.FC<CardProps> = ({ size }) => (
  <div>{size}</div>
);

Card.defaultProps = {
  size: 'small'
};

// Size is optional to the user
const Usage = () => (
  <Card />
)
```

Without React.FC:

```tsx
interface CardProps {
  // Key part right here is to make the defaulted prop not optional
  // this way in your function it won't be undefined
  size: 'small' | 'large';
}

// The type of size will be "string"
const Card = ({ size }: CardProps) => (
  <div>{size}</div>
);

// Typescript can use this defaultProps to determine what is optional
// for the user of your component.
Card.defaultProps = {
  size: 'small'
};

// Size is optional to the user
const Usage = () => (
  <Card />
)
```

**Comment by hipstersmoothie** [comment]
added docs: https://github.com/hipstersmoothie/storybook-addon-react-docgen/pull/76

I fixed it in your example (using `React.FC`) by changing:

```tsx
import React from "react";
// to
import * as React from "react";
```

**Comment by mattfelten** [comment]
This does work and shows default props in the prop table correctly.
```
export const Button: FC<ButtonProps> = ({
	fill = 'solid',
	primary,
	...props
}) => {
	var classes = 'Button';
	if (primary) classes += ' Button--primary';

	return <div className={classes} {...props} />;
}

Button.displayName = "Button";
```

**Comment by hipstersmoothie** [comment]
Oh interesting.

**Comment by NordlingDev** [comment]
None of above solutions work for me. This is my file:

```ts
import React, { FC } from "react";
import { ButtonProps } from "./button.props";

export interface ButtonProps {
    /** Label */
    label: string;
    /** Click handler */
    onClick?: () => void;
}

export const Button: FC<ButtonProps> = ({
    label,
    onClick,
}) => {
    return (
        <button onClick={onClick}>
            {label}
        </button>
    );
};

Button.displayName = "Button";
```

**Comment by mattfelten** [comment]
Can you see if it has to do with your `export default Button;` line? That's the only thing different between what I'm doing and what you're doing.

**Comment by NordlingDev** [comment]
@mattfelten . Actually if must've been something weird going on in my webpack config or something. I restarted another CRA project instead and added Storybook after that. Now it works.
