### ISSUE TITLE
Should support the "disabled" options prop

### ISSUE THREAD

**Issue by StJohn3D** [hipstersmoothie/storybook-addon-react-docgen#80]
Per the [StoryBook addon spec](https://storybook.js.org/docs/addons/writing-addons/#disabling-an-addon-panel)

This addon should support an options object like this
```js
props: { disabled: true }
```
Which would turn that tab off for the given story.

**Comment by hipstersmoothie** [comment]
PRs welcome!

**Comment by petermikitsh** [comment]
It's supported currently:

```tsx
// HelloWorld.stories.tsx

export default {
  title: 'Hello World',
  component: () => {},
  parameters: {
    props: {
      disable: true,
    },
  },
};

```

**Comment by hipstersmoothie** [comment]
Nice!
