### ISSUE TITLE
Shows wrong props

### ISSUE THREAD

**Issue by yury-cx** [hipstersmoothie/storybook-addon-react-docgen#82]
This addon added in global config.
If I add local module decorator for styles "@sambego/storybook-styles", like 
  decorators: [
    styles({
      width: '400px',
    }),
  ],
then it tries to show  props for this decorator:

Prop Types
“StyleDecorator” Component
No propTypes defined!

Adding this addon locally as first decorator solves problem for the module.

**Comment by hipstersmoothie** [comment]
I use the `propTablesExclude` property for that. This plugin works by looking at the jsx returned by your story function. if it is wrapper in a decorator this will get processed too
