### ISSUE TITLE
cannot read localeCompare property  of undefined 

### ISSUE THREAD

**Issue by ylji1990** [hipstersmoothie/storybook-addon-react-docgen#95]
![02137588-1A86-418E-B54D-54BB85E8BAAA](https://user-images.githubusercontent.com/38064469/78857978-98a94a00-7a5d-11ea-8d24-8b55e2b6cdbc.png)

should be check underfined

**Comment by hipstersmoothie** [comment]
@ylji1990 can you test with `1.2.32`?

**Comment by ylji1990** [comment]
> @ylji1990 can you test with `1.2.32`?

it was already ok with 1.2.32,  thanks.
